var q = 0;

var perspectiva = [
    "¿Crees que existe la amistad entre el hombre y la mujer?",
    "Cuando ayudas a alguien, ¿lo hacés por vos o por la otra persona? ¿Crees que existen las acciones desinteresadas?",
    "¿Elegimos lo que somos o nos lo impone nuestro entorno?",
    "'Es mejor pedir perdón que permiso' ¿Qué opinás sobre esta expresión?",
    "¿Qué mandatos o presiones creés que se imponen entre varones?",
    "Lo que una persona piensa ¿Creés que la define? ¿En qué medida y por qué?",
    "¿La educación escolar nos prepara para afrontar la adultez?",
    "¿Creés que todos tenemos un propósito en esta vida? ¿Cuál sentís que es el tuyo?",
    "'Dime con quién andas y te diré quién eres' ¿Qué pensas?",
    "¿Considerás importante la educación sexual? ¿Quiénes deberían abordar este tema?",
    "La educación que recibí me enseñó a ______________________________.",
    "¿Creés que hay alguna razón por la que naciste en tu familia?",
    "¿Creés que las personas pueden cambiar?",
    "¿Qué es el 'amor propio'?",
    "¿Qué creencias se le imponen a los niños y no estás de acuerdo?",
    "¿Qué es el exito para vos? ¿Evaluás diferentes formas de sentirte exitoso?",
    "Si tuvieras que volver a elegir tu género ¿cuál elegirías? ¿Por qué?",
    "¿Cómo definís una relación tóxica?",
    "¿Creés que existe el momento indicado para empezar o terminar un proyecto*? ¿Cómo te das cuenta? (*Por ejemplo, una relación, un trabajo, entre otros.)",
    "¿Vivir sin amor de amistad o sin amor de pareja?",
    "¿El fin justifica los medios?",
    "¿Cuándo creés que es importante tenér noción sobre la sexualidad?",
    "Un buen resultado, aunque sin esfuerzo, ¿vale menos?",
    "¿Creés en las segundas oportunidades?",
    "¿Qué temas considerás tabú? ¿Por qué?",
    "¿Qué pensás sobre la monogamia?",
    "¿Casualidad o causalidad?",
    "¿Creés que llega un momento en el que nos sentimos realizados?",
    "El lenguaje, ¿cómplice o enemigo de la inclusión social?",
    "¿Todo lo que pensamos es porque lo deseamos? ¿Por qué?",
    "¿Qué diferencias creés que existen entre el amor y el enamoramiento?",
    "Una mujer toma la iniciativa en una relación heterosexual, ¿qué pensás?",
    "¿Creés que una persona adulta puede aprender de una jóven? ¿En qué sentido?",
    "¿Existe la media naranja? ¿Creés que necesitamos algo o alguien externo para sentirnos completos?",
    "¿Creés que vamos camino a una sociedad sin estereotipos? ¿Considerás que es una señal de evolución?",
    "¿Creés que se puede hacer humor con todo? ¿Qué pensás?",
    "¿Creés que existe una razón por la que te rodeas de ciertas personas?",
    "¿Alguna vez dejaste de hacer algo por tu género?",
    "'Si no te cela, no te quiere' ¿Qué opinás sobre esta expresión?",
    "¿Qué pensás sobre la demostración afectiva en público?",
    "¿Qué es ser libre en una relación de pareja? ¿Qué diferencias encontrás con otros vínculos que mantenes?",
    "'Elegí un trabajo que te guste y no vas a tener que trabajar ni un día de tu vida' ¿Qué pensás?",
    "¿Qué es la sexualidad para vos?",
    "'Detrás de un gran hombre, hay una gran mujer' ¿Qué pensás?",
    "¿Qué pensás sobre la educación sin distinción de géneros?",
    "¿Qué cambiarías del mundo?",
    "¿Qué o quién influye en la forma en que pensas? ¿Por qué?",
    "¿Se puede estar bien con los demás sin estar bien con uno mismo?"
];

var presentación = [
    "¿Te sentís libre de tomar tus propias decisiones?",
    "¿Te define la opinión de los demás?",
    "Nombra tres características que te definan.",
    "¿De qué halago estás más orgulloso?",
    "¿Qué primera impresión crees que das?",
    "¿Qué actividades te divertían antes y ahora no?",
    "Si tuvieses que elegir una profesión, trabajo o carrera distinta, ¿cuál sería?",
    "Cuando eras chico, ¿cómo te imaginabas siendo adulto?",
    "¿Sos idealista o realista? ¿Cómo impacta en tu vida y en tus relaciones?",
    "¿Una situación que te incomode?",
    "¿Un momento simple que disfrutes?",
    "¿Reconoces tus defectos? ¿Y tus virtudes? ¿Cuáles son?",
    "¿Te enamoraste alguna vez? ¿Quién fue la primera persona y qué te gustó de ella?",
    "¿Te gusta reflexionar solo o con otras personas? ¿Qué temas despiertan tu curiosidad últimamente?",
    "Quiero o tengo. ¿Cuál de las dos está más presente en tu cotidianidad?",
    "Si tuvieras que elegir una persona para que te acompañe en una experiencia espiritual, ¿quién sería? ¿Por qué?",
    "¿Cuándo fue la última vez que hiciste algo por primera vez? ¿Qué fue?",
    "¿Qué actitudes no te gustan pero las toleras en una persona? ¿Cuál valoras?",
    "¿Qué disfrutas de tu cotidianidad? ¿Y qué no?",
    "¿Hay alguna actividad que te guste tanto que te haga perder la noción del tiempo?",
    "La razón o la emoción, ¿cuál de las dos tiene más peso en vos? ¿Te gusta que sea así o preferirías que fuera al revés?",
    "¿Qué actividades tendes a dejar para después?",
    "¿Qué amas y la mayoría de la gente no?",
    "Perdonar o pedir perdón, ¿cuál te cuesta más?",
    "¿Qué destacas de las personas que te criaron?",
    "¿Con qué tipo de personalidad solés conectar?",
    "Esta semana me puse contento por ____________",
    "¿Te asusta el futuro? ¿Por qué?",
    "¿Cuál fue tu primera impresión de la persona que tenés a tu izquierda?",
    "¿Tomás decisiones porque te sentís preparado o porque son las esperadas para tu edad?",
    "¿Qué aventura tenés pendiente por realizar?",
    "¿Qué buscas en una pareja?",
    "¿Tenés alguna fuente de motivación hoy en día? ¿Cuál es o podría ser?",
    "Pensás más en el 'por qué' o en el 'para qué' de las cosas?",
    "¿Te permitís mostrate vulnerable? ¿Con quién?",
    "¿Una buena decisión?",
    "Si pudieses ser exitoso en lo que quieras, ¿en qué elegirías serlo?",
    "¿Qué destacas de tus amistades?",
    "¿Te dedicas tiempo a vos mismo? ¿Qué hacés en esos momentos?",
    "¿Solés culpar a otras personas por lo que te pasa? ¿En qué situaciones?",
    "¿Te considerás una persona prejuiciosa? ¿Por qué?",
    "¿Una persona que te alivie en momentos tristes?",
    "¿Qué sensaciones tuviste en tu primer día de universidad / trabajo? Si no tuviste esas experiencias, ¿qué esperas de ellas?",
    "Cuando te sentís bien con vos mismo, ¿con quién te gustaría estar?",
    "Los domingos son... ¿Deprimentes o disfrutables? ¿Te gusta arrancar la semana?",
    "Nombra a alguien que te inspire.",
    "¿Cómo reaccionas ante una actitud que te molesta?",
    "¿Qué momentos del día elegís para reflexionar?"
];

var profundidad = [
    "¿Cómo y por qué empezaste a tener conocimiento sobre la sexualidad? ¿Te hubiese gustado que sea de otra forma?",
    "¿Cómo te ves en esta etapa?",
    "¿Cuál es tu mayor miedo?",
    "¿Qué etiquetas sentís que acarreas y no te identifica?",
    "¿Cuándo fue la última vez que dijiste 'Te quiero'? ¿A quién se lo dijiste?",
    "¿Sentís que te quedó algo pendiente con alguna persona? ¿Por qué no hiciste nada al respecto?",
    "¿Un recuerdo valioso de tu infancia?",
    "¿Alguna vez tuviste un acto valioso con alguien, del que no presumas mucho, pero te hace sentir orgulloso?",
    "¿Sos obsesivo? ¿En qué sentido?",
    "¿Una decisión difícil?",
    "¿Qué estás listo para soltar?",
    "Sólo yo sé que soy ______________.",
    "¿Una persona o una experiencia que te haya marcado?",
    "Destacá una virtud de alguna de las personas presentes.",
    "Si mirás al pasado, ¿cómo ves al adolescente que fuiste?",
    "¿Cómo manejás los desencuentros en los vinculos? (Por ejemplo, amistades que dejas de frecuentar)",
    "¿Cuáles son tus próximos objetivos por cumplir?",
    "Si pudieses conocer los sentimientos más profundos de una persona, ¿a quién elegirías? ¿Por qué?",
    "¿Qué te da culpa?",
    "¿Qué mandatos traés y parecés?",
    "¿Qué aprendiste de vos este último año?",
    "¿Cómo canalizas tu enojo? ¿Y tu tristeza?",
    "¿Hay algún momento en que te sientas solo estando acompañado?",
    "¿Alguna vez fingiste afecto por una persona? ¿Por qué?",
    "¿Qué lugar ocupa el deseo en tu vida?",
    "Si pudieses volver al pasado y cambiar algo, ¿qué sería? ¿Por qué?",
    "¿Qué creencia te gustaría desaprender?",
    "¿Cuál es el sueño más grande que tenés?",
    "¿Qué exigencias te ponés? ¿Haces algo para suavizarlas?",
    "¿Cuándo fue la última vez que lloraste? ¿Por qué?",
    "¿Qué cambiarías de tu crianza si tuvieras que educar a una persona?",
    "¿Qué rol cumplís en tu familia? ¿Cómo te hace sentir?",
    "¿Tuviste amistades que no fueron sanas? ¿Cómo lo manejaste?",
    "Pensá en alguien que te gustaría abrazar ¿Quién es?",
    "¿Cuál es el mejor consejo que te dieron? ¿Pudiste transmitírselo a alguien también?",
    "¿Qué pensabas el día de tu casamiento? Si no te casaste, ¿te gustaría?",
    "¿Dejaste de hacer cosas por miedo a fracasar? ¿Cuáles?",
    "Describí tu relación con vos mismo.",
    "¿Te gustaría hacerle una pregunta a una de las personas presentes? Hacesela.",
    "¿Qué es la soledad para vos? ¿Te gusta estar solo? ¿Por qué?",
    "¿Alguna vez escuchaste o leíste una conversación sin permiso? ¿Por qué?",
    "¿Te mentís a vos mismo sobre algo? ¿Por qué?",
    "Si pudieras volver al pasado, ¿qué te dirías?",
    "¿Qué pensabas el día que nació tu primer hijo? Si no tenés, ¿te gustaría tener?",
    "¿Qué tan cómodo te sientes hablando sobre la sexualidad?",
    "¿Hay algún aspecto de tu personalidad que te cuesta aceptar? ¿Buscas rechazarlo o integrarlo en tu vida?",
    "Siendo grande, ¿cómo te hubiese gustado ser de chico?",
    "¿Qué estás trabajando en tu interior y te gustaría compartir?"
];

var descomprimir = [
    "¿Cuál es tu lugar preferido de tu casa? ¿Por qué?",
    "¿Qué fantasía te gustaría bajar a la realidad?",
    "¿Qué actividad extrema te gustaría hacer?",
    "¿Cuáles son tus tres placeres culposos?",
    "¿Cuál era tu juego o juguete favorito de la infancia?",
    "¿Qué título le pondrías a una película sobre tu vida?",
    "¿Volver al pasado o ir al futuro? ¿Por qué?",
    "Si pudieses crear un feriado, ¿por qué motivo sería?",
    "¿Con quién fue tu primer beso? ¿Qué sentiste?",
    "Tres cosas que te gusta hacer y sentís que te salen mal.",
    "¿El último regalo que hiciste? ¿Y el último regalo que recibiste?",
    "Si fueses embajador, ¿qué lugar eligirías para irte a vivir? ¿A dónde NO irías?",
    "¿En qué momento del día tenés tus mejores ideas?",
    "Si escribieras un libro, ¿de qué sería? ¿Cómo lo titularías?",
    "¿Qué es lo que más te gusta del barrio donde vivís?",
    "¿Qué tres deseos pedías cuando eras niño? ¿Y ahora?",
    "Si fueses de otro género, ¿qué sería lo primero que harías?",
    "¿Un sueño recurrente?",
    "¿Una canción que te alegre?",
    "¿Qué recuerdo tenés de tu primera cita?",
    "Compartí un miedo absurdo que tengas.",
    "¿Quién de las personas presentes sería mejor comediante?",
    "¿Un pensamiento recurrente?",
    "¿Tu libro preferido?",
    "¿Qué es lo primero que mirás en una persona?",
    "¿Qué personaje de película o serie te gustaría ser?",
    "¿Un viaje pendiente?",
    "Si algo te gusta, ¿asumirías cualquier riesgo?",
    "Si fueses un objeto, ¿cuál te gustaría ser?",
    "Tres cosas que te hacen sentir felíz.",
    "¿Te animarías a vivir una experiencia en el extranjero? ¿Cuál?",
    "¿Tuviste alguna experiencia paranormal? ¿Cómo fué y con quién/es estabas?",
    "Si fueses un animal, ¿cuál sería? ¿Por qué?",
    "¿Tu película preferida?",
    "Un talento inútil que te de orgullo es _____________",
    "¿Crees en el amor a primera vista?",
    "¿Sobre qué tema considerás que tenés mucho conocimiento?",
    "Si fueses una persona famosa, ¿quién serías? ¿Por qué?",
    "¿Qué cuento te relataban en la infancia?",
    "¿Cuál es el mejor lugar que conociste?",
    "¿Qué canción elegirías para cantar en un karaoke?",
    "Tres cosas que te den vergüenza ajena.",
    "Si pudieras crear tu lugar en el mundo, ¿cómo sería?",
    "¿Una situación vergonzosa que recuerdes?",
    "¿Elegirías otra época para vivir? ¿Cuál y por qué?",
    "¿En qué te gustaría haber sido bueno?",
    "¿Qué comida te recuerda a tu hogar?",
    "¿Algo ridículo por lo que te gustaría que te paguen?"
];

function startGame() {
  q++;
  var pick1 = Math.floor(Math.random() * perspectiva.length);
  var pick2 = Math.floor(Math.random() * presentación.length);
  var pick3 = Math.floor(Math.random() * profundidad.length);
  var pick4 = Math.floor(Math.random() * descomprimir.length);
  
  if (q == 1) {
    document.getElementById("text").innerHTML = (perspectiva[pick1]);
    document.getElementById("btn").innerHTML = "Siguiente pregunta";
  } else if (q == 2) {
    document.getElementById("text").innerHTML = (presentación[pick2]);
  } else if (q == 3) {
    document.getElementById("text").innerHTML = (profundidad[pick3]);
  } else if (q == 4) {
    document.getElementById("text").innerHTML = (descomprimir[pick4]);
  } else if (q == 5) {
    document.getElementById("text").innerHTML = "¡Fin del juego!";
    document.getElementById("btn").innerHTML = "Volver al inicio";
  } else if (q == 6) {
    location.href = "../index.html";
  }
}